name: Build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_target: linux
            build_path: build/linux/x64/release/bundle
            artifact_name: linux-release
          - os: ubuntu-latest
            build_target: apk
            build_path: build/app/outputs/flutter-apk/app-release.apk
            artifact_name: android-release
          - os: windows-latest
            build_target: windows
            build_path: build/windows/x64/runner/Release
            artifact_name: windows-release
          - os: macos-latest
            build_target: macos
            build_path: build/macos/Build/Products/Release
            artifact_name: macos-release
          - os: macos-latest
            build_target: ios
            build_path: build/ios/iphoneos/komiyomi.ipa
            artifact_name: ios-release

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.27.2

      - name: Setup Java for Android
        if: matrix.build_target == 'apk'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest' && matrix.build_target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        if: matrix.build_target == 'ios'
        run: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos
          zip -r -q komiyomi.ipa Payload

      - name: Build ${{ matrix.build_target }}
        if: matrix.build_target != 'ios'
        run: flutter build ${{ matrix.build_target }} --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.build_path }}
